spring:
  datasource:
    url: jdbc:mysql://localhost:3306/genesis?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: genesis
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      schema-locations: classpath*:/database/schema.sql
      platform: h2
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
  servlet:
    multipart:
      max-file-size: 120MB
      max-request-size: 120MB
  main:
    allow-circular-references: true

storage:
  path: src/main/resources/static/video-storage/

logging:
  level:
    org.springframework.security: DEBUG
